# Header
menu:
  Home: /
  Archives: /archives
  # About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: 最佳编程书籍 # The best Programming books.

# Theme Secondary subtitle
susbtitle_secondary: 经典书籍，精挑细选，集于一处  # Compiling thousands of lists and recommendations, all in one place.

# Footer About Section
about_footer: "每个书单最多只列了25本，如果一项技能看完25本书都学不会，更多的书也无济于事。贪多嚼不烂，集中精力看好书。"

# Default post title
default_post_title: bestbooks.dev

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: # klugjo
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/nanyangbuyi
# facebook_url: https://www.facebook.com/
# instagram_url: https://www.instagram.com/
# dribble_url: https://dribbble.com/
# github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
# googleplus_url: https://plus.google.com/
# behance_url: https://www.behance.net/
# fivehundredpx_url: https://500px.com/
email_url: mailto:nanyangbuyi@hotmail.com
# rss_url: \#
